image: python:latest

# variables:
#   PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# cache:
#   paths:
#     - .cache/pip

# stages:
#   - test
#   - review
#   - deploy

# checkinstall:
#   stage: test
#   script:
#     - make install
#     - make update
#     - make clean

# Ruff:
#   stage: review
#   script:
#     - pip install ruff
#     - ruff .

# pytest:
#   stage: test
#   script:
#     - pip install .
#     - pip install pytest
#     - pytest .

# deploy:
#   stage: deploy
#   variables:
#     GIT_STRATEGY: none
#   only:
#     - main
#   script:
#     - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
#     - eval $(ssh-agent -s)
#     - chmod 400 "$SSH_PRIVATE_KEY"
#     - ssh-add "$SSH_PRIVATE_KEY"
#     - mkdir -p ~/.ssh
#     - chmod 700 ~/.ssh
#     - ssh {Deployment Server} -oStrictHostKeyChecking=no "{deploy_script}"
